### ISSUE TITLE
Disabling sidekick for a repo where the pre-push hook was not installed throws error

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#105]
Add repo.
Do not enable pre-push.
Remove repo.

Hi. I'm using Sidekick version: 0.13.2 and I'm getting the following error:
message:`
ENOENT: no such file or directory, open '/Users/andy/Library/Application Support/sidekick/Sidekick-DemoRepo/.git/hooks/pre-push'
Error: ENOENT: no such file or directory, open '/Users/andy/Library/Application Support/sidekick/Sidekick-DemoRepo/.git/hooks/pre-push'
    at Error (native)
    at Object.fs.openSync (fs.js:546:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:134:20)
    at Object.fs.readFileSync (fs.js:396:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:381:29)
    at Object.exports.deleteHook (/Users/andy/code/sidekick/sk-deployed/app/core/config/repoConfig.js:79:24)
    at callFunction (/Users/andy/code/sidekick/sk-deployed/build/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:116:18)
    at EventEmitter.<anonymous> (/Users/andy/code/sidekick/sk-deployed/build/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:212:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:179:7)
    at EventEmitter.<anonymous> (/Users/andy/code/sidekick/sk-deployed/build/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:96:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7) /Users/andy/code/sidekick/sk-deployed/build/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:77:15`
stack:`
Error: ENOENT: no such file or directory, open '/Users/andy/Library/Application Support/sidekick/Sidekick-DemoRepo/.git/hooks/pre-push'
Error: ENOENT: no such file or directory, open '/Users/andy/Library/Application Support/sidekick/Sidekick-DemoRepo/.git/hooks/pre-push'
    at Error (native)
    at Object.fs.openSync (fs.js:546:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:134:20)
    at Object.fs.readFileSync (fs.js:396:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:381:29)
    at Object.exports.deleteHook (/Users/andy/code/sidekick/sk-deployed/app/core/config/repoConfig.js:79:24)
    at callFunction (/Users/andy/code/sidekick/sk-deployed/build/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:116:18)
    at EventEmitter.<anonymous> (/Users/andy/code/sidekick/sk-deployed/build/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:212:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:179:7)
    at EventEmitter.<anonymous> (/Users/andy/code/sidekick/sk-deployed/build/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:96:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7) /Users/andy/code/sidekick/sk-deployed/build/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:77:15
    at metaToValue (/Users/andy/code/sidekick/sk-deployed/build/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:77:15)
    at RemoteMemberFunction (/Users/andy/code/sidekick/sk-deployed/build/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:111:26)
    at Object.module.exports.exports [as deleteHook] (file:///Users/andy/code/sidekick/sk-deployed/app/browser/dist/bundle.js:56455:23)
    at stopAnalysingRepo (file:///Users/andy/code/sidekick/sk-deployed/app/browser/dist/bundle.js:62710:16)
    at HTMLDivElement.self.stopAnalysingRepoModal.$.modal.onApprove (file:///Users/andy/code/sidekick/sk-deployed/app/browser/dist/bundle.js:62731:9)
    at HTMLDivElement.e.fn.modal.r.each.S.event.approve (file:///Users/andy/code/sidekick/sk-deployed/app/browser/dist/semantic/semantic.min.js:16:328)
    at HTMLDivElement.n.event.dispatch (file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/jquery/dist/jquery.min.js:3:6466)
    at HTMLDivElement.n.event.add.r.handle (file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/jquery/dist/jquery.min.js:3:3241)`

**Comment by rishson** [comment]
So when adding a new repo - the pre-push should be enabled by default and the user can remove it if they want.
