### ISSUE TITLE
issue in `0.13.2`

### ISSUE THREAD

**Issue by timruffles** [sidekickcode/tracker#111]
``` sh
[daemon 94360] uncaught: TypeError: undefined is not a function
    at ensureWeHaveHaveComparisonTargetLocally (/Applications/Sidekick.app/Contents/Resources/app/daemon/push/update-process.js:151:16)
    at BranchUpdateProcess.self.start (/Applications/Sidekick.app/Contents/Resources/app/daemon/push/update-process.js:77:12)
    at processUpdate (/Applications/Sidekick.app/Contents/Resources/app/daemon/push/push-process.js:86:19)
    at nextUpdate (/Applications/Sidekick.app/Contents/Resources/app/daemon/push/push-process.js:70:7)
```

**Comment by rishson** [comment]
@timruffles  - I'll close this now we have 0.14.1 done. The issues was resolved in that version.
