### ISSUE TITLE
Re-analysis no longer works

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#167]
`analysis.reanalyse` is called, but results is:

```
2015-12-15T15:30:52.565Z [gui-main 5442] [rpc] /common/rpc/index.js:349 node write { id: 22,
  type: 'result',
  error:
   { name: 'Error',
     message: 'NoSuchMethod',
     stack: 'Error: NoSuchMethod\n    at callIncoming (/Users/andy/code/sidekick/sk-deployed/app/common/rpc/index.js:328:19)\n    at Parser.incoming (/Users/andy/code/sidekick/sk-deployed/app/common/rpc/index.js:273:14)\n    at emitOne (events.js:77:13)\n    at Parser.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:146:16)\n    at Parser.Readable.push (_stream_readable.js:110:10)\n    at Parser.Transform.push (_stream_transform.js:128:32)\n    at Parser._transform (/Users/andy/code/sidekick/sk-deployed/app/node_modules/newline-json/parser.js:27:12)\n    at Parser.Transform._read (_stream_transform.js:167:10)\n    at Parser.Transform._write (_stream_transform.js:155:12)\n    at doWrite (_stream_writable.js:292:12)\n    at writeOrBuffer (_stream_writable.js:278:5)\n    at Parser.Writable.write (_stream_writable.js:207:11)\n    at MainIPCStream.ondata (_stream_readable.js:525:20)\n    at emitOne (events.js:77:13)\n    at MainIPCStream.emit (events.js:169:7)',
     method: 'reanalyse',
     params:
      [ '57341d39-6185-4bcc-a8e0-34acac116873',
        'push11.js',
        'var x\nvar y\n\nfunction init(){\n  reallyerally\n  //bad code \n}\n\nfunction someFun(){\n  log(\'asdasd\')\n}' ] } }
```

**Comment by timruffles** [comment]
ey? In push or normal? As in your can't edit code?

**Comment by rishson** [comment]
Whenever editing a file. Initial analysis of the file is fine, but after editing and `reanalyse` is called, the error above is thrown by the node side of rpc.
