### ISSUE TITLE
Starting gui from push no longer works

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#176]
Analysis finds an issue in modified lines, and tries to start gui:

```
2016-01-07T11:23:41.869Z [gui-main 73740] [analysis-listener] /daemon/push/analysis-listener.js:107 found an issue in modified lines
2016-01-07T11:23:41.870Z [gui-main 73740] [push] /daemon/push/index.js:89 booting UI to deal with issues found
2016-01-07T11:23:41.871Z [gui-main 73740] [push] /daemon/push/index.js:97 sending gui intent
2016-01-07T11:23:41.915Z [gui-main 73740] /daemon/expose/index.js:29 serving
2016-01-07T11:23:41.916Z [gui-main 73740] [rpc] /common/rpc/index.js:194 node exposed callActor
2016-01-07T11:23:41.916Z [gui-main 73740] [rpc] /common/rpc/index.js:194 node exposed -getActorProperty-
2016-01-07T11:23:41.916Z [gui-main 73740] [rpc] /common/rpc/index.js:194 node exposed reloadConfig
2016-01-07T11:23:41.916Z [gui-main 73740] [rpc] /common/rpc/index.js:194 node exposed pushStart
2016-01-07T11:23:41.916Z [gui-main 73740] [rpc] /common/rpc/index.js:194 node exposed pushStartGui
2016-01-07T11:23:41.917Z [gui-main 73740] [rpc] /common/rpc/index.js:194 node exposed pushSkip
2016-01-07T11:23:41.917Z [gui-main 73740] [rpc] /common/rpc/index.js:194 node exposed commitAndPush
2016-01-07T11:23:41.917Z [gui-main 73740] [rpc] /common/rpc/index.js:194 node exposed fileModifications
2016-01-07T11:23:41.917Z [gui-main 73740] [rpc] /common/rpc/index.js:194 node exposed possibleComparisonTargets
2016-01-07T11:23:41.917Z [gui-main 73740] [rpc] /common/rpc/index.js:194 node exposed analysisStart
2016-01-07T11:23:41.917Z [gui-main 73740] [rpc] /common/rpc/index.js:194 node exposed writeFile
2016-01-07T11:23:41.918Z [gui-main 73740] /main/gui.js:116 exposed
2016-01-07T11:23:41.981Z [gui-main 73740] /main/errors.js:16 unhandled promise rejection: TypeError: createWindow(...).then is not a function
    at EventEmitter.exports.intent (/Users/andy/code/sidekick/sk-deployed/app/main/gui.js:30:8)
    at sendPushIntent (/Users/andy/code/sidekick/sk-deployed/app/daemon/push/index.js:98:14)
    at PushProcess.bootUiIfRequired (/Users/andy/code/sidekick/sk-deployed/app/daemon/push/index.js:90:5)
    at PushProcess.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at PushProcess.emit (events.js:166:7)
    at PushProcess.actor.emit (/Users/andy/code/sidekick/sk-deployed/app/common/rpc/actors.js:93:21)
    at BranchUpdateProcess.handle (/Users/andy/code/sidekick/sk-deployed/app/common/events.js:31:19)
    at emitNone (events.js:67:13)
    at BranchUpdateProcess.emit (events.js:166:7)
    at BranchUpdateProcess.actor.emit (/Users/andy/code/sidekick/sk-deployed/app/common/rpc/actors.js:93:21)
    at EventEmitter.handle (/Users/andy/code/sidekick/sk-deployed/app/common/events.js:31:19)
    at emitNone (events.js:72:20)
    at EventEmitter.emit (events.js:166:7)
    at foundFirstIssue (/Users/andy/code/sidekick/sk-deployed/app/daemon/push/analysis-listener.js:86:9)
    at /Users/andy/code/sidekick/sk-deployed/app/node_modules/lodash/index.js:7173:25
```

**Comment by rishson** [comment]
Later, gui does look like it is notified:

```
2016-01-07T11:23:43.078Z [gui-main 73740] /main/gui.js:34 calling intent { id: 'c1c62cbb-9bb9-45ed-9148-ff4c46f4b689',
  type: 'push',
  remote: 'origin',
  url: 'git@github.com:timruffles/sk-deployed.git',
  actions:
   [ { id: '5237bdcf-0504-465a-82f1-df6615653b31',
       localRef: 'refs/heads/dev',
       localSha: '5521f0a98aad4041222d5ffe9ba69992cacf3a59',
       remoteRef: 'refs/heads/dev',
       remoteSha: '81d73822267caaa4f69bb7d2a7e1a24a28df361d',
       type: 'update-branch',
       localBranch: 'dev',
       remoteBranch: 'dev' } ],
  repoPath: '/Users/andy/code/sidekick/sk-deployed' }
2016-01-07T11:23:43.079Z [gui-main 73740] [rpc] /common/rpc/index.js:385 node-call-3 request method: intent params: [{"id":"c1c62cbb-9bb9-45ed-9148-ff4c46f4b689","type":"push","remote":"origin","url":"git@github.com:timruffles/sk-deployed.git","actions":[{"id":"5237bdcf-0504-465a-82f1-df6615653b31","localRef":"refs/heads/dev","localSha":"5521f0a98aad4041222d5ffe9ba69992cacf3a59","remoteRef":"refs/heads/dev","remoteSha":"81d73822267caaa4f69bb7d2a7e1a24a28df361d","type":"update-branch","localBranch":"dev","remoteBranch":"dev"}],"repoPath":"/Users/andy/code/sidekick/sk-deployed"}]
2016-01-07T11:23:43.081Z [gui-main 73740] [rpc] /common/rpc/index.js:349 node write { id: 1, type: 'notified' }
```

**Comment by rishson** [comment]
Ahh - `push.branchUpdates()` no longer return the repo path in a `branchUpdate`.

![screen shot 2016-01-07 at 11 48 46 am](https://cloud.githubusercontent.com/assets/468596/12169965/adf64fc2-b534-11e5-8e64-3e349ebaeb3d.png)

We rely on it being there are we need to then read the `.sidekickrc` file for the repo when creating meta.

**Comment by rishson** [comment]
Fixed repoPath issue - now pass through from push definition rather than branchUpdate.
Still not getting analysis results through though.

**Comment by rishson** [comment]
So for push, the following works ok: start analysis, get list of analysed files, get modifications for file.
The analysis of the files runs, but the results are never streamed back into the Annotations live array.
Quite alot of this in the logs:

```
2016-01-08T10:10:54.951Z [gui-main 74604] /main/errors.js:16 unhandled promise rejection: Error: Timeout
    at /Users/andy/code/sidekick/sk-deployed/app/common/promiseHelpers.js:24:21
    at result (/Users/andy/code/sidekick/sk-deployed/app/common/promiseHelpers.js:83:7)
    at Timer.listOnTimeout (timers.js:89:15)
```

**Comment by rishson** [comment]
@timruffles Does this look correct to you for the public api of `update-process`:

```
// public API
  proxied("files")
  proxied("reanalyse");
  proxied("files");
```

See previous comment for the issues I'm getting (no analysis progress events for a push). Is the analysis progress not being exposed?

**Comment by rishson** [comment]
List of all things that look wrong in logs:

```
2016-01-11T11:19:26.727Z [gui-main 74604] [rpc] /common/rpc/index.js:269 node received { id: 5,
  type: 'call',
  method: 'callActor',
  params: [ 'e08589cb-6b2b-49fc-9a75-fbdb9db0f6c8', 'state' ] }
2016-01-11T11:19:26.727Z [gui-main 74604] [rpc] /common/rpc/index.js:321 node incomingCall callActor [ 'e08589cb-6b2b-49fc-9a75-fbdb9db0f6c8', 'state' ]
2016-01-11T11:19:26.727Z [gui-main 74604] [rpc] /common/rpc/index.js:300 sendError 5 { [Error: ActorNoSuchMethod] method: 'state' }
2016-01-11T11:19:26.728Z [gui-main 74604] [rpc] /common/rpc/index.js:349 node write { id: 5,
  type: 'result',
  error:
   { name: 'Error',
     message: 'ActorNoSuchMethod',
     stack: 'Error: ActorNoSuchMethod\n    at runCall (/Users/andy/code/sidekick/sk-deployed/app/common/rpc/actors.js:112:21)\n    at process._tickCallback (node.js:368:9)',
     method: 'state' } }
2016-01-11T11:19:26.730Z [gui-main 74604] [rpc] /common/rpc/index.js:269 node received { id: 6,
  type: 'call',
  method: 'callActor',
  params: [ 'e08589cb-6b2b-49fc-9a75-fbdb9db0f6c8', 'state' ] }
```

```
2016-01-11T11:19:26.855Z [gui-main 74604] [rpc] /common/rpc/index.js:349 node write { id: 9,
  type: 'result',
  result:
   { analysed:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     notAnalysed: [ [Object], [Object], [Object], [Object], [Object] ] } }
2016-01-11T11:19:26.897Z [gui-main 74604] /main/errors.js:16 unhandled promise rejection: Error: Timeout
    at /Users/andy/code/sidekick/sk-deployed/app/common/promiseHelpers.js:24:21
    at result (/Users/andy/code/sidekick/sk-deployed/app/common/promiseHelpers.js:83:7)
    at Timer.listOnTimeout (timers.js:89:15)
```

**Comment by rishson** [comment]
So in `browser/src/analyses`:

```
function getAnnotations(id) {
  var actor = rpc().getActor(id);

  var annotations = live(actor.call("state"));
  var events = addEvents(annotations);

  actor.on("fileAnalyserEnd", function(err, file, analyser, result) {
    if(!err) {
      var byAnalyser = annotations[file.path] || (annotations[file.path] = {});
      byAnalyser[analyser.analyser] = result;
      events.trigger("data", file, analyser, result);
    }
  });

  return annotations;
}
```

Don't think `state` is correct - cannot see it emitted anywhere.

**Comment by timruffles** [comment]
Heya - sorry about this - will debug tonight! `.call` is a method call,
not an event.

**Comment by rishson** [comment]
```
2016-01-19T16:06:13.175Z [cli 21689] /common/shell.js:30 execAtPath: git rev-parse --symbolic-full-name 'refs/heads/new-demo'
2016-01-19T16:06:13.191Z [cli 21689] [prepush] /cli/ui/prepush.js:114 about to run validations
2016-01-19T16:06:13.191Z [cli 21689] [prepush] /cli/ui/prepush.js:132 running isFastForwardOrCreate
2016-01-19T16:06:13.192Z [cli 21689] /common/shell.js:30 execAtPath: git merge-base --is-ancestor 481e46c0d372ae4c9c1b2fe1e595757d84db09b4 5b0b77957781b40a34d570b4d5c7b696f2a4ec9d
2016-01-19T16:06:13.206Z [cli 21689] [prepush] /cli/ui/prepush.js:132 running hasConfig
2016-01-19T16:06:13.213Z [cli 21689] /common/log/index.js:131 { exclude: [],
  languages: { js: { analysers: [ 'js-todos', 'jscs', 'eslint' ] } } }
2016-01-19T16:06:13.214Z [cli 21689] [prepush] /cli/ui/prepush.js:132 running isPushingCurrentBranch
2016-01-19T16:06:13.215Z [cli 21689] /common/shell.js:30 execAtPath: git rev-parse --abbrev-ref HEAD
2016-01-19T16:06:13.225Z [cli 21689] [prepush] /cli/ui/prepush.js:195 prepush: {"remote":"origin","url":"git@github.com:rishson/demo.git","actions":[{"localRef":"refs/heads/new-demo","localSha":"5b0b77957781b40a34d570b4d5c7b696f2a4ec9d","remoteRef":"refs/heads/new-demo","remoteSha":"481e46c0d372ae4c9c1b2fe1e595757d84db09b4","type":"update-branch","localBranch":"new-demo","remoteBranch":"new-demo"}],"repoPath":"/Users/andy/code/gh/demo"}
2016-01-19T16:06:13.235Z [cli 21689] [prepush] /cli/ui/prepush.js:260 sending pushStart
2016-01-19T16:06:13.236Z [cli 21689] [rpc] /common/rpc/index.js:314 request cli2main:1 method: pushStart params: [{"id":"6562106c-c422-436f-b5ff-d1b4d59abfe2","type":"push","remote":"origin","url":"git@github.com:rishson/demo.git","actions":[{"id":"79bebb1a-a6c2-4b0d-ba5e-8d1533d6af78","localRef":"refs/heads/new-demo","localSha":"5b0b77957781b40a34d570b4d5c7b696f2a4ec9d","remoteRef":"refs/heads/new-demo","remoteSha":"481e46c0d372ae4c9c1b2fe1e595757d84db09b4","type":"update-branch","localBranch":"new-demo","remoteBranch":"new-demo"}],"repoPath":"/Users/andy/code/gh/demo"}]
2016-01-19T16:06:13.237Z [cli 21689] /cli/MainProcess.js:55 attempting to connect to main, retries 0, err 'undefined'
2016-01-19T16:06:13.237Z [cli 21689] /cli/MainProcess.js:89 connecting
2016-01-19T16:06:13.242Z [cli 21689] /cli/MainProcess.js:55 attempting to connect to main, retries 1, err 'connect ECONNREFUSED 127.0.0.1:42043'
2016-01-19T16:06:13.242Z [cli 21689] /cli/MainProcess.js:63 booting main
2016-01-19T16:06:13.242Z [cli 21689] [gui-control] /common/gui-control/index.js:28 dev spawn of ui
2016-01-19T16:06:14.138Z [cli 21689] /cli/MainProcess.js:83 spawn fail { [Error: ChildExit] code: 1, signal: null }
2016-01-19T16:06:14.139Z [cli 21689] /cli/ui/index.js:92 unhandled promise rejection! Error: CouldNotSpawnMain
    at /Users/andy/code/sidekick/sk-deployed/app/cli/MainProcess.js:84:15
    at tryCatcher (/Users/andy/code/sidekick/sk-deployed/app/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/andy/code/sidekick/sk-deployed/app/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/andy/code/sidekick/sk-deployed/app/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/andy/code/sidekick/sk-deployed/app/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/andy/code/sidekick/sk-deployed/app/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/andy/code/sidekick/sk-deployed/app/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/andy/code/sidekick/sk-deployed/app/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
2016-01-19T16:06:38.241Z [cli 21689] [prepush] /cli/ui/prepush.js:190 UNEXPECTED FAILURE Error: TimeoutWaitingForWriteAck<cli2main:1,call,duration: 25000>
    at null._onTimeout (/Users/andy/code/sidekick/sk-deployed/app/common/promiseHelpers.js:37:21)
    at Timer.listOnTimeout (timers.js:92:15)
2016-01-19T16:06:38.241Z [cli 21689] [prepush] /cli/ui/prepush.js:79 exiting with code '1' with msg 'sidekick suffered an unexpected failure' Error: TimeoutWaitingForWriteAck<cli2main:1,call,duration: 25000>
    at null._onTimeout (/Users/andy/code/sidekick/sk-deployed/app/common/promiseHelpers.js:37:21)
    at Timer.listOnTimeout (timers.js:92:15)
2016-01-19T16:06:38.242Z [cli 21689] /cli/ui/index.js:83 exit 1
```

**Comment by rishson** [comment]
getting:

```
2016-01-20T16:27:58.973Z [gui-main 22018] /main/errors.js:16 unhandled promise rejection: Error: TimeoutWaitingForWriteAck<main2cli:1527,notify,duration: 500>
    at null._onTimeout (/Users/andy/code/sidekick/sk-deployed/app/common/promiseHelpers.js:37:21)
    at Timer.listOnTimeout (timers.js:92:15)
```

for every analysed file in a push (not including initial state - which is fine).

I'm on latest `dev`, but I had to change `rpc.end` to 'rpc.off`in`app/main/gui.js` to get things this far.

**Comment by timruffles** [comment]
so this is ok
