### ISSUE TITLE
Issues with ipc after upgrading electron

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#181]
Upgraded electron to 0.36.4 (to get ELECTRON_RUN_AS_NODE working).
`ipc` module has moved, but I think the issues lies in our windowRpc code:

```
2016-01-19T15:38:36.767Z [gui-main 20434] /main/errors.js:11 unhandled exception: TypeError: listener must be a function
    at EventEmitter.removeListener (events.js:276:15)
    at RpcPair.self.off.self.removeListener (/Users/andy/code/sidekick/sk-deployed/app/common/rpc/index.js:180:35)
    at BrowserWindow.<anonymous> (/Users/andy/code/sidekick/sk-deployed/app/main/gui.js:120:21)
    at BrowserWindow.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:169:7)
```

**Comment by rishson** [comment]
from `gui.js`
replaced

```
// should be callable multiple times for reloading in dev
  function exposeRpc() {
    // cleanup when reloading
    if(newWindow.rpc) {
      newWindow.rpc.end();
      log("cleaning up on page RPC (after dev refresh)");
    }
```

with

```
// should be callable multiple times for reloading in dev
  function exposeRpc() {
    // cleanup when reloading
    if(newWindow.rpc) {
      newWindow.rpc.off();
      log("cleaning up on page RPC (after dev refresh)");
    }
```

as was getting `newWindow.rpc.end is not a function` errors - could only see `off` in the code.

**Comment by timruffles** [comment]
should be ok - this was leftover code from streaming
