### ISSUE TITLE
issue on push to new branch

### ISSUE THREAD

**Issue by timruffles** [sidekickcode/tracker#199]
<img width="1147" alt="screen shot 2016-02-19 at 11 27 38" src="https://cloud.githubusercontent.com/assets/249800/13174483/d608aa1c-d6fb-11e5-9fc1-86c7cc7c4d93.png">

**Comment by rishson** [comment]
Hi. I'm using Sidekick version: 0.16.0 and I'm getting the following error:
message:`
Cannot read property 'processError' of undefined`
stack:`
TypeError: Cannot read property 'processError' of undefined
    at handleFiles (file:///Users/andy/code/sidekick/sk-deployed/app/browser/dist/bundle.js:41774:56)
    at processQueue (file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/angular/angular.js:14745:28)
    at file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/angular/angular.js:14761:27
    at Scope.$eval (file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/angular/angular.js:15989:28)
    at Scope.$digest (file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/angular/angular.js:15800:31)
    at file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/angular/angular.js:16028:26
    at completeOutstandingRequest (file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/angular/angular.js:5507:10)
    at file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/angular/angular.js:5784:7`

**Comment by rishson** [comment]
Hi. I'm using Sidekick version: 0.16.0 and I'm getting the following error:
message:`
Cannot read property 'totals' of undefined`
stack:`
TypeError: Cannot read property 'totals' of undefined
    at Object.fn (file:///Users/andy/code/sidekick/sk-deployed/app/browser/dist/bundle.js:47335:54)
    at Scope.$digest (file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/angular/angular.js:15826:29)
    at file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/angular/angular.js:16028:26
    at completeOutstandingRequest (file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/angular/angular.js:5507:10)
    at file:///Users/andy/code/sidekick/sk-deployed/app/browser/node_modules/angular/angular.js:5784:7`

**Comment by rishson** [comment]
```
2016-02-19T21:40:10.233Z [gui-main 69516] [analysis-session] /daemon/analysis-session/AnalysisSession.js:123 analysing 265 files
2016-02-19T21:40:10.234Z [gui-main 69516] [analysis-session] [analysis] [[commit] ] [[analysis:app/Gruntfile.js] ] [[js-todos] ] /analysis/src/file_analysis.js:53 start
2016-02-19T21:40:10.240Z [gui-main 69516] [analysis-session] [analysis] [[commit] ] [[analysis:app/Gruntfile.js] ] [[jscs] ] /analysis/src/file_analysis.js:53 start
2016-02-19T21:40:10.240Z [gui-main 69516] [analysis-session] [analysis] [[commit] ] [[analysis:app/Gruntfile.js] ] [[eslint] ] /analysis/src/file_analysis.js:53 start
2016-02-19T21:40:10.242Z [gui-main 69516] [analysis-session] [analysis] [[commit] ] /analysis/lib/agent.js:39 fileEnd
2016-02-19T21:40:10.244Z [gui-main 69516] /main/errors.js:16 unhandled promise rejection: ReferenceError: file is not defined
    at Object.exports.run (/Users/andy/code/sidekick/sk-deployed/app/analysis/src/analyser.js:35:19)
    at runAnalyser (/Users/andy/code/sidekick/sk-deployed/app/analysis/src/file_analysis.js:57:34)
    at /Users/andy/code/sidekick/sk-deployed/app/analysis/src/file_analysis.js:33:12
    at Promise.apply (/Users/andy/code/sidekick/sk-deployed/app/node_modules/async-q/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/Users/andy/code/sidekick/sk-deployed/app/node_modules/async-q/node_modules/q/q.js:741:41)
    at /Users/andy/code/sidekick/sk-deployed/app/node_modules/async-q/node_modules/q/q.js:1304:14
    at flush (/Users/andy/code/sidekick/sk-deployed/app/node_modules/async-q/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

**Comment by rishson** [comment]
Only seems to happen the first time you try to push.
Push to new branch, gui opens - analysis occurs, but analysis progress does not seem to make it to gui.
Reload gui (dev mode) and retry - all is well.

**Comment by rishson** [comment]
Maybe a timing issue with fetching files and listening for annotations.
