### ISSUE TITLE
Push can fail if call to GA times out

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#254]
```
2016-06-09T11:55:24.057Z [gui-main 18266] /main/errors.js:16 unhandled promise rejection: Error: getaddrinfo ENOTFOUND www.google-analytics.com www.google-analytics.com:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

**Comment by rishson** [comment]
Gets itself into an endless loop - 2000+ `unhandled promise rejection` errors when trying to push but with GA was down.

**Comment by timruffles** [comment]
Okay, have made tracking failures just log a message!
