### ISSUE TITLE
Gui does not receive analysis events when pushing to new branch

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#274]
For every file analysed when pushing to new branch, we get a `main2cli` exception (due to an EPIPE).

```
2016-07-18T10:28:48.394Z [gui-main 91162] /main/errors.js:16 unhandled promise rejection: Error: TimeoutWaitingForWriteAck<main2cli:6282,notify,duration: 500>
    at null._onTimeout (/Users/andy/code/sidekick/sk-deployed/app/common/promiseHelpers.js:52:21)
    at Timer.listOnTimeout (timers.js:92:15)
```

then GA tries to log this:

```
method: 'get',
  headers:
   { Accept: 'application/json, text/plain, */*',
     'User-Agent': 'axios/0.8.1' },
  agent: undefined,
  auth: undefined,
  userCallback: [Function: handleResponse] }
  follow-redirects options +1ms { maxRedirects: 5,
  protocol: 'https:',
  host: 'www.google-analytics.com',
  port: null,
  path: '/debug/collect?tid=UA-40226431-3&v=1&cid=e9012d42-6cea-474f-b658-7f4bd9063bc2&cd1=0.17.4&t=exception&exd=TimeoutWaitingForWriteAck%3Cmain2cli:6346,notify,duration:+500%3EError:+TimeoutWaitingForWriteAck%3Cmain2cli:6346,notify,duration:+500%3E%0A++%2Fapp%2Fcommon%2FpromiseHelpers.js:52:21)%0A++(timers.js:92:15)&exf=0',
```

**Comment by rishson** [comment]
To reproduce:

try to push to a new branch
cli starts
gui starts to choose comparison branch
choose branch and click 'analyse'
analysis occurs, but events never make it through to the ui

I think this is to do with the rpc in main to gui - when hooking onto an existing AnalysisSession, the analysis events are not making it through to the gui.

Session somehow gets poisoned - any attempt to run standalone analysis on the repo results in the EPIPE behaviour below:

**Comment by rishson** [comment]
For every file analysed when pushing to new branch, we get a `main2cli` exception (due to an EPIPE).

```
2016-07-18T10:28:48.394Z [gui-main 91162] /main/errors.js:16 unhandled promise rejection: Error: TimeoutWaitingForWriteAck<main2cli:6282,notify,duration: 500>
    at null._onTimeout (/Users/andy/code/sidekick/sk-deployed/app/common/promiseHelpers.js:52:21)
    at Timer.listOnTimeout (timers.js:92:15)
```

then GA tries to log this:

```
method: 'get',
  headers:
   { Accept: 'application/json, text/plain, */*',
     'User-Agent': 'axios/0.8.1' },
  agent: undefined,
  auth: undefined,
  userCallback: [Function: handleResponse] }
  follow-redirects options +1ms { maxRedirects: 5,
  protocol: 'https:',
  host: 'www.google-analytics.com',
  port: null,
  path: '/debug/collect?tid=UA-40226431-3&v=1&cid=e9012d42-6cea-474f-b658-7f4bd9063bc2&cd1=0.17.4&t=exception&exd=TimeoutWaitingForWriteAck%3Cmain2cli:6346,notify,duration:+500%3EError:+TimeoutWaitingForWriteAck%3Cmain2cli:6346,notify,duration:+500%3E%0A++%2Fapp%2Fcommon%2FpromiseHelpers.js:52:21)%0A++(timers.js:92:15)&exf=0',
```

**Comment by timruffles** [comment]
The exception you've listed is in the main2cli portion.

I'd check whether events are being sent from the main process first. Then take a look at whether the GUI can connect to main.

**Comment by timruffles** [comment]
![2016-08-12 16_13_36](https://cloud.githubusercontent.com/assets/249800/17627074/c7586cec-60a7-11e6-93b8-072064d02d23.gif)

**Comment by timruffles** [comment]
👍 goodbye annoying bug!
