### ISSUE TITLE
Overzealous error handling

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#78]
On support-new-branches.
If an analyser throws an error (in this case js-todos finds an unexpected identifier in a file), we do the following:

report the error on the console
create a valid annotation for the error (so we can see it in the file view)
create a fatal error that then causes a runtime error in the stream
show the toaster with the runtime error

This means that the analysis 'fails' as far as the UI is concerned.
@timruffles Should we not treat this as `stream.on('error')` rather than stream fatal because we want to continue the analysis and report the user errors to the UI?

**Comment by rishson** [comment]
demon-log:

```
[daemon 26267] [analysis-session] [analysis] [[commit] ] [[analysis:new_unstaged.js] ] [[js-todos] ] Exited with exit code '1', stdout:

stderr:
/Users/andy/code/sidekick/sk-deployed/app/analysers/js-todos/node_modules/js-todos/node_modules/esprima/esprima.js:3872
            throw e;
                  ^
Error: Line 4: Unexpected identifier
    at throwError (/Users/andy/code/sidekick/sk-deployed/app/analysers/js-todos/node_modules/js-todos/node_modules/esprima/esprima.js:1156:21)
    at throwUnexpected (/Users/andy/code/sidekick/sk-deployed/app/analysers/js-todos/node_modules/js-todos/node_modules/esprima/esprima.js:1199:13)
    at consumeSemicolon (/Users/andy/code/sidekick/sk-deployed/app/analysers/js-todos/node_modules/js-todos/node_modules/esprima/esprima.js:1295:13)
    at parseStatement (/Users/andy/code/sidekick/sk-deployed/app/analysers/js-todos/node_modules/js-todos/node_modules/esprima/esprima.js:2804:9)
    at /Users/andy/code/sidekick/sk-deployed/app/analysers/js-todos/node_modules/js-todos/node_modules/esprima/esprima.js:3609:38
    at parseSourceElement (/Users/andy/code/sidekick/sk-deployed/app/analysers/js-todos/node_modules/js-todos/node_modules/esprima/esprima.js:3062:20)
    at parseSourceElements (/Users/andy/code/sidekick/sk-deployed/app/analysers/js-todos/node_modules/js-todos/node_modules/esprima/esprima.js:3095:29)
    at parseProgram (/Users/andy/code/sidekick/sk-deployed/app/analysers/js-todos/node_modules/js-todos/node_modules/esprima/esprima.js:3109:19)
    at /Users/andy/code/sidekick/sk-deployed/app/analysers/js-todos/node_modules/js-todos/node_modules/esprima/esprima.js:3609:38
    at Object.parse (/Users/andy/code/sidekick/sk-deployed/app/analysers/js-todos/node_modules/js-todos/node_modules/esprima/esprima.js:3856:23)

[daemon 26267] [analysis-session] [analysis] [[commit] ] [[analysis:new_unstaged.js] ] [[js-todos] ] end error: non zero exit code
```

**Comment by rishson** [comment]
console:

```
[26264:1006/095516:INFO:CONSOLE(49263)] "(stream) fatal", source: file:///Users/andy/code/sidekick/sk-deployed/app/browser/dist/bundle.js (49263)
[26264:1006/095516:INFO:CONSOLE(44383)] "[object Object]", source: file:///Users/andy/code/sidekick/sk-deployed/app/browser/dist/bundle.js (44383)
```

**Comment by rishson** [comment]
![screen shot 2015-10-06 at 10 10 39 a m](https://cloud.githubusercontent.com/assets/468596/10304507/91c9563e-6c12-11e5-9e0b-7310455e185d.png)
