### ISSUE TITLE
Unable to run standalone or comparison analysis for new branch.

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#93]
Here is the log when performing a push to a new branch. After choosing comparison (remote), we get 

```
[daemon 96184] [update] FAILED
[daemon 96184] [update] Error: 'Error: Command failed: /bin/sh -c git fetch origin error-log
fatal: Couldn't find remote ref error-log
' with error code 128, in path '/Users/andy/code/sidekick/sk-deployed'
stdout: 
stderr: fatal: Couldn't find remote ref error-log

[daemon 96184] [push] update err Error: 'Error: Command failed: /bin/sh -c git fetch origin error-log
fatal: Couldn't find remote ref error-log
' with error code 128, in path '/Users/andy/code/sidekick/sk-deployed'
stdout: 
stderr: fatal: Couldn't find remote ref error-log

    at /Applications/Sidekick.app/Contents/Resources/app/common/shell.js:31:21
    at ChildProcess.exithandler (child_process.js:692:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:953:16)
    at Socket.<anonymous> (child_process.js:1114:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe._onclose (net.js:455:12)
[daemon 96184] [push] push ending,  err:Error: 'Error: Command failed: /bin/sh -c git fetch origin error-log
fatal: Couldn't find remote ref error-log
' with error code 128, in path '/Users/andy/code/sidekick/sk-deployed'
stdout: 
stderr: fatal: Couldn't find remote ref error-log
 status:undefined
[daemon 96184] [push] disposed

```

**Comment by rishson** [comment]
@timruffles I know you fixed loads of stuff to do with passing args to git - just wondering if all the changes  are in master?

**Comment by rishson** [comment]
When performing standalone analysis - the analysis is performed fine, but the ui throws an assertion error on the start of analysis - am investigating.

**Comment by rishson** [comment]
Confirmed that this does _not_ effect standalone analysis of existing branches.
