### ISSUE TITLE
Push fails for existing branch

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#97]
Not a new branch - just a standard push.

```
[cli 17490] [prepush] UNEXPECTED FAILURE Error: 'Error: Command failed: /bin/sh -c git rev-parse --symbolic-full-name ''
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
' with error code 128, in path '/Users/andy/code/gh/demo'
stdout: 

stderr: fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at /Users/andy/code/sidekick/sk-deployed/app/common/shell.js:38:21
    at ChildProcess.exithandler (child_process.js:723:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:984:16)
    at Socket.<anonymous> (child_process.js:1153:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe.close (net.js:464:12)
[cli 17490] [prepush] exiting with code '1' with msg 'null' Error: 'Error: Command failed: /bin/sh -c git rev-parse --symbolic-full-name ''
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
' with error code 128, in path '/Users/andy/code/gh/demo'
stdout: 

stderr: fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at /Users/andy/code/sidekick/sk-deployed/app/common/shell.js:38:21
    at ChildProcess.exithandler (child_process.js:723:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:984:16)
    at Socket.<anonymous> (child_process.js:1153:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe.close (net.js:464:12)
[cli 17490] exit 1

```

**Comment by rishson** [comment]
We should report to the cli ui that something has gone wrong - as currently you only get the git push fail text.

**Comment by rishson** [comment]
daemon/push/update-process:

```
return git.ensureComparisonTargetPresent(
        repoPath
      , pushDefinition.remote
      , branchUpdate.remoteBranch
    )
    .catch(function() {
      return Promise.reject(new Error(`we could not find '${comparison.sha}' locally for comparison`));
    })

```

```
ensureComparisonTargetPresent
```

 is not a function in git, well, at least not one that has been committed.

**Comment by rishson** [comment]
Also, can you sprintf in js??

```
return gitAtPath(cwd, `rev-parse --symbolic-full-name '%s'`, query)
```

**Comment by timruffles** [comment]
You can if you call util.format, which inside gitAtPath is what's happening
:)

**Comment by rishson** [comment]
gitAtPath

```
function gitAtPath(repoPath, command) {
  var args = [repoPath, gitPath() + " " + command].concat(_.slice(arguments, 2));
  log('gitAtPath: ' + args);
  return execAtPath.apply(null, args);
}
```

gives

```
[daemon 18156] gitAtPath: /Users/andy/code/gh/demo,git ls-tree HEAD -- %s,push11.js
[daemon 18156] gitAtPath: /Users/andy/code/gh/demo,git ls-tree HEAD -- %s,new_unstaged.js
[daemon 18156] gitAtPath: /Users/andy/code/gh/demo,git diff %s -- %s,7c5a9cdac70d1e7c65502d5067cbef0ea3f6662d,push11.js
```

looks like we need to remove the sprintf placeholders?

**Comment by timruffles** [comment]
keep going down the call stack ;) execAtPath

**Comment by rishson** [comment]
Ahh - OK. I'll leave my extra logging in the code though as I find it useful to see the actual git commands that we are issuing :-)

Could you do a quick check to see if you have uncommitted code in daemon/git, specifically

```
git.ensureComparisonTargetPresent
```

which isn't a known function.

**Comment by rishson** [comment]
OK - implementing fix.

```
ensureComparisonTargetPresent
```

@timruffles I'm implementing as:

```
git ls-remote --heads [remote] [remote-branch]
```

Shout if you had something else in mind.
